name: 'github-commit-lint'
description: 'Checks commit message for proper format'
branding:
  icon: 'tag'
  color: 'gray-dark'
inputs:
  message:
    description: 'commit message'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
